### ISSUE TITLE
Missing Card Holder Field

### ISSUE THREAD

**Issue by rturk** [sbycrosz/react-native-credit-card-input#1]
Card Holder field it's a important field, cards can't be processed without cardholder.

**Comment by sbycrosz** [comment]
👍 
I'm thinking of putting `<CreditCardInput requiresName/>`
Thoughts?

**Comment by rturk** [comment]
@sbycrosz I would default cardholder field to always requierd since it is a mandatory requirement from credit card processors. Transactions without a Card Holder will be declined. What is optional is the CVV field.

Mandatory fields:
- Card Holder
- Credit card number
- Expire Date

Optional fields:
- CVV

**Note on why CVV is optional:**

Collecting CVV information increases the chances of transaction approval, however current regulation does not allow CVV data to be stored in a DB (not even encrypted). CVV can only be handled in memory so the App will have have to ask the CVV code every time a new transaction is performed. 

This is why this field is often ignored (not required) when 1click like transactions or subscriptions payments are required. For example Amazon.com don't ask for the CVV code.

**Comment by MattFoley** [comment]
I think `requiresName` is a good prop.

I'm thinking of using this project, and I don't actually need Card Holder name to be entered here, as our users have already entered this elsewhere. 

I do however need a zip code, is it possible to add that?

**Comment by rturk** [comment]
@MattFoley please note that what `cardHolder` field follows Credit Card regulation and constraints so it can be different than the real user name.

For example a person whose a real name is:
**Joe Fake User With Long Name the Third**

Will actually have a cardholder name written as:
**JOE FAKE USER W L THIRD**

**Comment by MattFoley** [comment]
Sure, but not everyone will handle that via the same entry form, so I'd think making it optional is a good idea.

**Comment by rturk** [comment]
@MattFoley yep, makes sense to be optional.

**Comment by sbycrosz** [comment]
So I guess, I'll create `requiresName`, `requiresCVC`, and `requiresPostalCode` props to toggles the respective fields.

Thanks for the input! I'll try to get it up soon ;)

**Comment by sibelius** [comment]
I think postal code is not related to the card itself, it should be handled by another component

Because u can have billing address and shipment address different

**Comment by rturk** [comment]
Hi @sbycrosz when do you think you'll code this? I would like to include your code in my next release and replace my Own credit Card view...

**Comment by rturk** [comment]
@sbycrosz I've created a PR with cardHolder Field Please review https://github.com/sbycrosz/react-native-credit-card-input/pull/3

**Comment by crookedneighbor** [comment]
RE: 

> @sbycrosz I recommend setting the cardholder field to always be required. This is a mandatory field based on credit card processors requirements. Transactions without a Card Holder will be declined. What is optional is the CVV field.

That's not strictly true. You can use Braintree or Stripe and not need to collect the cardholder name.

**Comment by rturk** [comment]
@crookedneighbor please note the full original discussion above 

> ..yep, makes sense to be optional

**Comment by sbycrosz** [comment]
![good](https://cloud.githubusercontent.com/assets/4867178/18609295/4a2a27aa-7d31-11e6-8c18-3e2d0d389295.jpg)

Now CreditCardInput supports `requiresName`, `requiresCVC`, and `requiresPostalCode`!

I'm not happy with the user must manually press on postalCode field from the name field because we can't determine if the user has finished typing the name or not. Not terribly sure on how to solve this 😦  (maybe putting the postalCode before name?)

Also will need to rework LiteCreditCardInput layout for those extra fields because on how it's currently implemented. **PRs are welcome**, ideally it should look like [this](http://www.lukew.com/ff/entry.asp?1667) but with name field.

**Comment by sbycrosz** [comment]
Yeah, I guess we'll reopen this when there's a need for it.

**Comment by itanhduy** [comment]
Hi all,
Any updates on this one?

**Comment by AlejandroAguilar99** [comment]
Hey! is there a way to implement this only using the card number? I mean, a prop like requireExpireDate: the other params will be entered in other components.
