### ISSUE TITLE
Non horizontal inputs (feature request)

### ISSUE THREAD

**Issue by BillyFigueroa** [sbycrosz/react-native-credit-card-input#100]
Is it possible to make the inputs vertically stacked? if not can we have an option to?

While this is a cool UI, less "savvy" users may get confused by this. For example, if I turn off autoFocus, they may not know to scroll to view the other fields. Someone forked this and made a more basic UI with stacked fields here

https://github.com/lexor90/react-native-credit-card-input

Is it possible to have a flag that allows you to default to this instead? something like inputOrientation="horizontal" or inputOrientation="stacked" or inputOrientation="vertical" etc

I guess I can just use their fork but I don't know that they will maintain their repo closely with this one so I may miss on updates or features. Do you think this is something you guys can offer? or am I supposed to use CardView instead and create my own fields? (This can be done but this a good amount of work and sort of defeats the purpose of using a component made by someone else when you have to customize it heavily)

**Comment by rodrigoxavier** [comment]
I like this idea. Right now I need a vertical form in my Credit Card data but I can't.
Hope we have this functionality soon.

**Comment by slorber** [comment]
+1, my clients just asked me to put this form vertically as the horizontal form is annoying and confusing for them. Until implemented I'll have to build my own form and use CardView. The fork above is not kept updated with features I need (translations, scale...)

**Comment by podvipodvert** [comment]
+1

**Comment by 7laria** [comment]
#129

**Comment by lauborges** [comment]
+1

**Comment by Bonissauro** [comment]
+1

**Comment by ShrutiGarg019** [comment]
Is there any updated option to align fields vertically instead to horizontally.

**Comment by ShrutiGarg019** [comment]
> #129

Thanks for leading to right solution.

**Comment by jpamarohorta** [comment]
Created a new PR for a vertical form [#137](https://github.com/sbycrosz/react-native-credit-card-input/pull/137) that allows rows with fields to be defined via props.

**Comment by SanchezQb** [comment]
In node_modules/react-native-credit-card-input/src/CreditCardInput.js
Check the ScrollView around line 163

```
<ScrollView ref="Form"
          horizontal //Remove this and you should have a vertical view
          keyboardShouldPersistTaps="always"
          scrollEnabled={allowScroll}
          showsHorizontalScrollIndicator={false}
          style={s.form}>
```

**Comment by ETLopes** [comment]
PR #146 created for vertical inputs also.
