### ISSUE TITLE
[Android] CreditCardInput crash when clear field 

### ISSUE THREAD

**Issue by pgonzalez** [sbycrosz/react-native-credit-card-input#11]
An error ocurrs when someone deletes a wrong credit card number in CreditCardInput component
![screenshot_20161013-152957](https://cloud.githubusercontent.com/assets/1370775/19361652/eb25bb4c-9159-11e6-8b0f-0a3209f7d376.png)

**Comment by sbycrosz** [comment]
Fixed by af075a95cc924413d6a67b400c43d7eed989a880
The error happens when AndroidTextInput loses the last of its color style property. Fixes is to set a default color to the TextInput.

lmk if 0.26 fix your problem @pgonzalez
