### ISSUE TITLE
Change card color

### ISSUE THREAD

**Issue by harikanammi** [sbycrosz/react-native-credit-card-input#113]
Hi, I am using this module...But how to change the card color in this module.....
Please give any suggestion....... Thank you in advance...
`cardImageFront` and `cardImageBack` is to change the card image
But, I want to change only color of the card.......

**Comment by vinicarra** [comment]
You cannot, the image's color defines the card color.

**Comment by RazaShehryar** [comment]
> Hi, I am using this module...But how to change the card color in this module.....
> Please give any suggestion....... Thank you in advance...
> `cardImageFront` and `cardImageBack` is to change the card image
> But, I want to change only color of the card.......

A late reply but you can always change the .js file. 

I've made the custom component for the card and used LinearGradient instead of background image.
