### ISSUE TITLE
how to set onChange func? 

### ISSUE THREAD

**Issue by Talkwondo** [sbycrosz/react-native-credit-card-input#116]
Hi,
I probably missed something.
can someone explain how to handle on change prop?
If i want to extract the number and the other fields to state object.

Thanks,

**Comment by ningacoding** [comment]
this should be a stackoverflow question, not a ticket, but i'll answer for help:
// render
<CreditCardInput onChange={this._onCreditCardChanged}

// outside render(){...}
private _onCreditCardChanged = (text) => {
        console.log(text);
    };

look at the log when running app.
