### ISSUE TITLE
Inputs styles

### ISSUE THREAD

**Issue by makasimenator** [sbycrosz/react-native-credit-card-input#12]
Hello, is it possible to set width to input fields passing it trough props?

**Comment by sbycrosz** [comment]
Hi @makasimenator
Currently all widths are hard-coded https://github.com/sbycrosz/react-native-credit-card-input/blob/master/src/CreditCardInput.js#L25-L31

Maybe we should expose them as props! e.g.

```js
<CreditCardInput 
    inputWidths={{
      number: 70,
      expiry: 40,
      cvc: 40,
      name: 100,
      postalCode: 40,
    }} />
```

What do you think?

**Comment by makasimenator** [comment]
Why not. This should help.

**Comment by sbycrosz** [comment]
Yeah I shouldn't hard-code them in the first place. Would you create a PR @makasimenator ?

**Comment by makasimenator** [comment]
Yes, i can. I wrote it locally, but i have not access to push a new branch.

**Comment by sbycrosz** [comment]
Nice! Now you'll need to fork this repo, push your changes, then open a PR!
https://help.github.com/articles/fork-a-repo/

**Comment by makasimenator** [comment]
Yes, i did it. I can't push my changes because I have not access for it. Maybe you'll add me as colaborator?

**Comment by sbycrosz** [comment]
Hi @makasimenator, you'll need to fork the repo with the fork button (instead of cloning)
![](https://github-images.s3.amazonaws.com/enterprise/11.10.340/user/assets/images/help/repository/fork_button.jpg)

Once you've done that you'll have a copy of this repo which you could freely push into (and your name will be shown on [network](https://github.com/sbycrosz/react-native-credit-card-input/network)

**Comment by sbycrosz** [comment]
Closing this until more people requires this

**Comment by b-cooper** [comment]
I've forked the repo and added a slew of style override props. Here is the PR https://github.com/sbycrosz/react-native-credit-card-input/pull/29

**Comment by rochapablo** [comment]
Would be nice if I could re-write the container style removing the padding [from](https://github.com/sbycrosz/react-native-credit-card-input/blob/master/src/LiteCreditCardInput.js)

```
const s = StyleSheet.create({
  container: {
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
```
