### ISSUE TITLE
How to Hide the CVC field ?

### ISSUE THREAD

**Issue by kiki-le-singe** [sbycrosz/react-native-credit-card-input#128]
Hi guys !

Is it possible to hide the CVC input field when we use the <LiteCreditCardInput /> component ?

thanks for your help :)

**Comment by Mr-Cool** [comment]
It can be hidden on the CreditCardInput component, not currently supported by the LiteCreditCardInput.

`<CreditCardInput
          requiresCVC={false}
        />`

Documentation pretty clear on that.

**Comment by kiki-le-singe** [comment]
@Mr-Cool thanks it works !
