### ISSUE TITLE
Using keyboardAvoiding view with react-native-credit-card-input, got warning: overriding previous layout animation with new one before the first began

### ISSUE THREAD

**Issue by sherryxiao1988** [sbycrosz/react-native-credit-card-input#13]
The warning is attached:
![image](https://cloud.githubusercontent.com/assets/1202426/19843536/7e78dd72-9f5e-11e6-92e0-9d91f63cfae0.png)

The app works fine, but this warning comes up. Can anyone help?
Thank you!

**Comment by sbycrosz** [comment]
It seems RN doesn't like it when there's more than a single LayoutAnimation call at the same time.
I'm not entirely sure how to fix this annoying warning, but PRs are welcome 🍺

**Comment by jeffreymendez1993** [comment]
Wrap it inside a scrollView as well. It should be KeyBoardAvoidingView > ScrollView > CardInput

**Comment by beausmith** [comment]
Related [ReactNative Github Issues](https://github.com/facebook/react-native/):
- https://github.com/facebook/react-native/issues/12663
- https://github.com/facebook/react-native/issues/10606
