### ISSUE TITLE
keyboardType="numeric" triggers custom keyboard on ios

### ISSUE THREAD

**Issue by IgorVanian** [sbycrosz/react-native-credit-card-input#133]
Original issue: https://github.com/facebook/react-native/issues/22392

This issue appeared while being tested on iPhone X. Impossible to change the keyboard type after it has been triggered.

**Comment by kumashiro17** [comment]
work around until fixed in Xcode 

```
    func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        if textField == yourField { textField.keyboardType = .numbersAndPunctuation }
        return true
    }
```

**Comment by DevPolo** [comment]
> work around until fixed in Xcode
> 
> ```
>     func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
>         if textField == yourField { textField.keyboardType = .numbersAndPunctuation }
>         return true
>     }
> ```

Where should we paste this code in Xcode?

**Comment by JulianKingman** [comment]
I think it goes in `RCTBackedTextInputDelegateAdapter.m`, @kumashiro17 can you confirm?
