### ISSUE TITLE
# Attempted to redefine property 'style' on android with LiteCreditCard and debug mode false

### ISSUE THREAD

**Issue by davidducluzeaud** [sbycrosz/react-native-credit-card-input#139]
Hi folks ! I have a bug on android when I have the package installed on Android with debug mode off. Everything else works fine on iOS and android with the debug mode ON. My error is this One. 
Thanks 😉

![image (7)](https://user-images.githubusercontent.com/42339184/54912873-d9d1c900-4ef1-11e9-80c5-667a3a304d25.png)

**Comment by Ravi448** [comment]
Facing same issue, 
Anyone have any fix yet?

**Comment by Mattimus333** [comment]
Looks like this is an issue with https://github.com/moschan/react-native-flip-card where they have a duplicate style prop.  

https://github.com/moschan/react-native-flip-card/issues/75

**Comment by Moshman20** [comment]
the error is coming from a dependency library (react-native-flip-card).
To fix this go to 

>  node_modules/react-native-flip-card/lib/FlipCard.js,

 search for TouchableOpacity and remove the duplicate `style={{flex:1}}`

**Comment by PetteriHaro** [comment]
Getting the same problem. 

Don't have react-native-flip-card in my dependencies.

**Comment by Moshman20** [comment]
Okay, does it work in the debug mode?

**Comment by PetteriHaro** [comment]
@Moshman20 Works perfectly in debug mode on android and in both modes on iOS

**Comment by Moshman20** [comment]
@PetteriHaro Can you share a screenshot of your node_modules folder. (the area around react-native-credit-card-input folder). Something like this
![image](https://user-images.githubusercontent.com/41248079/55159411-3dadf900-5161-11e9-829e-f1285154b907.png)

**Comment by PetteriHaro** [comment]
Don't know if it's a dep of a dep but I deleted node_modules and ran npm install again and react-native-flip-card appeared in my node_modules. Your earlier fix on the `style={{flex:1}}` worked perfectly. @Moshman20 Thanks!

**Comment by Moshman20** [comment]
Nice! @PetteriHaro Good luck.

**Comment by davidducluzeaud** [comment]
The PR https://github.com/moschan/react-native-flip-card/issues/75 has been merged ! I can't test if the dependencies have been upgrade, because i did my own card validator but it is just to keep the issue up to data.
