### ISSUE TITLE
Input is Invisible

### ISSUE THREAD

**Issue by HowHai** [sbycrosz/react-native-credit-card-input#15]
I am having trouble getting this component to show up. The input is not visible. I am on RN 0.36.0 and this is for iOS. Any help appreciated! Here is what it looks like:

![img_8414](https://cloud.githubusercontent.com/assets/4635501/20570341/13f84f4e-b158-11e6-84cd-3d3096143818.JPG)

**Comment by sbycrosz** [comment]
Hey @HowHai 

Did you manage to fix this problem?
I just updated the example to RN36, and while I found a minor bugs on LiteCreditCardInput that I fixed in 0.2.8, I couldn't replicate this issue :/

-Sam
