### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by yuritoledo** [sbycrosz/react-native-credit-card-input#150]

**Comment by lcsvcn** [comment]
don't think so brogramer

**Comment by yuritoledo** [comment]
I forked it, and i gonna add some features, fix, etc.

https://github.com/yuritoledo/react-native-credit-card-input

**Comment by wagnerdelima** [comment]
What of the project? Is it alive? Is security updates a vulnerability to be avoided?

**Comment by yuritoledo** [comment]
@wagnerdelima i'm building a new version of this project. I guess this is abandoned 
If you want to contribute, here is the link: https://github.com/yuritoledo/react-native-credit-card-input

**Comment by wagnerdelima** [comment]
@yuritoledo I'd be happy to help. Do you have a branch with possible changes already?

**Comment by yuritoledo** [comment]
I glad to read this!
I recreated the repo, please check it (i don't know if u starred it)

I don't have a branch to it yet, feel free to contribute by your own way.

Any help is welcome
