### ISSUE TITLE
Pending Security Update !!!

### ISSUE THREAD

**Issue by lcsvcn** [sbycrosz/react-native-credit-card-input#152]
( ! ) Update **lodash** to last version
( ! ) Update **card-validator** to last version

![Captura de Tela 2019-08-21 às 16 54 06](https://user-images.githubusercontent.com/6011385/63463823-5b436e00-c434-11e9-9158-fa9b091af2ba.png)

**Comment by yuritoledo** [comment]
Hello guy

I created a fork of this one: https://github.com/yuritoledo/react-native-credit-card-input/

I am fixing the security issues and will add new features in future.

PR are welcome!
