### ISSUE TITLE
saved payment methods from play store

### ISSUE THREAD

**Issue by razan94** [sbycrosz/react-native-credit-card-input#158]
Hey , I faced a problem with this library , if I have payment methods added on my play store account then when I try to add payment method on the app where I use this component then it start filling the information from google account and that results on wrong behavior. dose anyone face similar thing or has any idea about this problem ?

**Comment by Vluf** [comment]
I have exactly the same issue. After completing the Google CVC check, it tries to fill in the form and starts flickering uncontrollably.

**Comment by tomasgarba** [comment]
We are facing the same issue on Android. After selecting saved payment method UI starts flickering uncontrollably.

**Comment by andre0799** [comment]
we are also facing the same issue here 👍

**Comment by tomasgarba** [comment]
I have fixed that for now in my fork https://github.com/tomasgarba/react-native-credit-card-input/commit/df68de1b4ea68c473e054dba20e5f7a77beb383d
