### ISSUE TITLE
Can't pass testID to run my e2e test

### ISSUE THREAD

**Issue by smakosh** [sbycrosz/react-native-credit-card-input#161]
## Details
- I'm using `additionalInputsProps` prop to pass a `testID` for each input but `Detox` is failing to type anything there or replace the text.

## Example
```js
<LiteCreditCardInput
  onChange={handleCreditCardInput}
  additionalInputsProps={{
    number: {
      testID: 'stripe-input-credit-card',
    },
    expiry: {
      testID: 'stripe-input-expiry',
    },
    cvc: {
      testID: 'stripe-input-cvc',
    },
  }}
/>
```

**Comment by smakosh** [comment]
@sbycrosz 👀

**Comment by Damimd10** [comment]
Hi @smakosh  I test it with the same component and works for me, can you paste an example of your test code, please?

**Comment by smakosh** [comment]
> Hi @smakosh I test it with the same component and works for me, can you paste an example of your test code, please?

Sure will do tomorrow morning

**Comment by smakosh** [comment]
Hey @Damimd10, Could you share your code snippet here.

I'm using Detox and here's the error log:
<img width="459" alt="Screen Shot 2020-01-22 at 19 55 42" src="https://user-images.githubusercontent.com/20082141/72924699-abab5880-3d51-11ea-8f58-ad1af6a55f04.png">

And here's my code snippet

```jsx
<LiteCreditCardInput
  onChange={handleCreditCardInput}
  inputStyle={styles.creditCardInput}
  additionalInputsProps={{
    number: {
      testID: 'stripe-input-credit-card',
    },
    expiry: {
      testID: 'stripe-input-expiry',
    },
    cvc: {
      testID: 'stripe-input-cvc',
    },
  }}
/>
```

**Comment by designervoid** [comment]
this is working on Android, but not working on iOS

**Comment by designervoid** [comment]
@smakosh are you using javascript in your e2e tests?

**Comment by smakosh** [comment]
> @smakosh are you using javascript in your e2e tests?

Detox

**Comment by designervoid** [comment]
@smakosh yeah i understanding that. me too. but my tests written on typescript.

**Comment by designervoid** [comment]
here an [example](https://gist.github.com/solkaz/ead11515e2aa91d0dc04e609b3108841)
