### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by aymkin** [sbycrosz/react-native-credit-card-input#165]
Please update the following components: CCInput, CreditCardInput, FlipCard

**Comment by kvlknctk** [comment]
lazy coders everywhere.

**Comment by godguide1** [comment]
When will this be update please?

**Comment by marquinmpfs** [comment]
When will this be update please? ²

**Comment by mayursarode4** [comment]
You can hide those yellow box waring's by adding below line in App.js or in .js file where your are using this library,

e.g:
 `
import { CreditCardInput } from "react-native-credit-card-input";`
`console.disableYellowBox = true;
`
For temporary basis/till the admin updates the changes.

**Comment by retronoodle** [comment]
+1 for getting this updated - thanks!

**Comment by nawedfarooque** [comment]
You can open node_modules/react-native-credit-card-input/src/CCInput.js
and replace componentWillReceiveProps with componentDidUpdate.

**Comment by designervoid** [comment]
https://github.com/sbycrosz/react-native-credit-card-input/issues/185#issuecomment-753360922

**Comment by designervoid** [comment]
@mayursarode4 i think disable warnings is bad practice. in your example you are disabling global yellow box, nope?
