### ISSUE TITLE
My input fields are getting cut off

### ISSUE THREAD

**Issue by ldunphy1** [sbycrosz/react-native-credit-card-input#17]
![untitled](https://cloud.githubusercontent.com/assets/22159844/20738655/b58622da-b682-11e6-820a-f89e60cd1e04.png)

**Comment by sbycrosz** [comment]
Hi @ldunphy1 , which React Native versions are you using?

**Comment by sbycrosz** [comment]
Let's track this at https://github.com/sbycrosz/react-native-credit-card-input/issues/14
