### ISSUE TITLE
lodash depedency version causing vulnerabilities 

### ISSUE THREAD

**Issue by reneerrusso** [sbycrosz/react-native-credit-card-input#179]
Lodash dependency version is too low causing vulnerabilities below.

https://npmjs.com/advisories/1065
https://npmjs.com/advisories/782

Need version 4.17.13 or later. 
Please update lodash dependency or change the way dependencies are installed for this package this way we can use our own version of lodash. 

Thanks! :D 

<img width="572" alt="Screen Shot 2020-08-22 at 1 25 53 PM" src="https://user-images.githubusercontent.com/20302877/90962074-30db2500-e47b-11ea-875e-14b2e3d592fb.png">

**Comment by gumiranda** [comment]
yeah, fix this please
