### ISSUE TITLE
Error browserify: export * from "./src/";  in index.js:1

### ISSUE THREAD

**Issue by alexisross** [sbycrosz/react-native-credit-card-input#18]
Hi,
Sorry I'm relatively new in the NodeJs world.
When I use browserify in my project I have this error since I use the 'react-native'credit-cart-input' module:

> [00:35:17] Starting 'browserify'...
> Error : 
> D:\dev\myproject\node_modules\react-native-credit-card-input\index.js:1
> export * from "./src/";
> ^
> ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Here my gulp task for Browserify:
```json
gulp.task('browserify', function(){
    return browserify({
        extensions: ['.js', '.jsx', '.es6', '.json'],
        entries: 'src/js/main.jsx',
    })
    .transform(babelify.configure({
        presets: ["es2015","react"],
    }))
    .bundle()
    .on("error", function (err) { console.log("Error : " + err.message); })
    .pipe(source('main.js'))
    .pipe(gulp.dest(path.DIST_JS));
});
```

I see the project use eslint, may be something is missing about this in my dev environnement.

Can you help me ?

**Comment by sbycrosz** [comment]
Hi @alexisross , 

This library only supports React Native (for building mobile apps) instead of React (for building web apps) at this moment :(

-Sam
