### ISSUE TITLE
Card Number in CreditCardInput not updating on smaller screen

### ISSUE THREAD

**Issue by hackson-jall** [sbycrosz/react-native-credit-card-input#183]
When using an iPhone 8 on Expo with React Native, I am seeing this behavior with the card number. The card image is resizing, but the card number is not.

![CreditCardInputBug](https://user-images.githubusercontent.com/25995543/94053759-bf0f3780-fda8-11ea-8ad1-a7e3b814e925.jpg)

**Comment by sandeeptapse** [comment]
I have the same problem! Is there a solution to this problem?
