### ISSUE TITLE
cardImageFront not working for iOS 14

### ISSUE THREAD

**Issue by goldqwert** [sbycrosz/react-native-credit-card-input#184]
cardImageBack and cardImageFront is not working for iOS 14

**Comment by thiagocsfoz** [comment]
not solution for this?

**Comment by calliday** [comment]
Have you tried updating react-native to 0.63? There is a known image display issue with RN 0.62 and iOS 14 (0.60 and 0.61 also?). Images don't show up for me using iOS 14 and RN 0.62.2, so I upgraded to 0.63.x and they work. If this uses images, it could be the problem. I haven't tried it with this library yet though.
