### ISSUE TITLE
How to configure form vertically?

### ISSUE THREAD

**Issue by jcaviedesc** [sbycrosz/react-native-credit-card-input#189]
How to setup form inputs vertically?

```
<view>
 <card/>
 <input />
 <input />
 <input />
</view>
```

**Comment by ManhVuTien** [comment]
In ```https://github.com/sbycrosz/react-native-credit-card-input/blob/master/src/CreditCardInput.js``` remove prop `horizontal`

**Comment by a7i7** [comment]
Is it possible to expose this as prop?
