### ISSUE TITLE
RN 0.39 broken container 

### ISSUE THREAD

**Issue by RomuxX** [sbycrosz/react-native-credit-card-input#19]
Hi,
Missed `flex: 1` in CreditCardInput.js row 18 .

`container: {
    alignItems: "center",
    flex: 1
  },`

Regards

**Comment by sbycrosz** [comment]
Hi @RomuxX ,

Could you try 0.3.0 ? 
I haven't add those `{ flex: 1 }`, but then it looks fine on the RN0.39 Example project.

-Sam

**Comment by sbycrosz** [comment]
Should be fixed @latest
