### ISSUE TITLE
How can i add a submit button and send all the form values?

### ISSUE THREAD

**Issue by ryan2412** [sbycrosz/react-native-credit-card-input#198]
`_onChange = (formData) => console.log(JSON.stringify(formData, null, ' '))

<View style={s.container}>
          <CreditCardInput
            autoFocus
            allowScroll
            requiresName
            requiresCVC
            requiresPostalCode
            labelStyle={s.label}
            inputStyle={s.input}
            validColor={'black'}
            invalidColor={'red'}
            placeholderColor={'darkgray'}
            onFocus={this._onFocus}
            onChange={this._onChange}
            onSubmit={this.componentDidMount()}
          />
          <Button
            title="Submit"
            buttonStyle={AppStyles.button}
            containerStyle={Metrics.verticalPadding}
            titleStyle={[AppStyles.buttonTitle, Helpers.w75]}
            onPress={this._onChange}
          />
        </View>`

Console gives `undefined```

**Comment by NickM101** [comment]
For me, I added setState to formdata on _onChange so that I can receive all the data upon completion
