### ISSUE TITLE
Error while updating property 'color' of a view managed by: AndroidTextInput

### ISSUE THREAD

**Issue by corymsmith** [sbycrosz/react-native-credit-card-input#20]
This happens when I put in an invalid value (text turns red) then delete values until its valid again.

Its the same error as #11, any idea how I can sort this? I'm using 0.3.0

**Comment by corymsmith** [comment]
Turns out I didn't have a color, only a fontSize in my inputStyle prop. May want to make sure that a color is added if there isn't one to avoid this. Unfortunately I don't have the time to put together and test a PR at the moment

**Comment by sbycrosz** [comment]
Definitely a regression from #11 , Thanks @corymsmith

**Comment by sbycrosz** [comment]
Fixed @0.3.1
