### ISSUE TITLE
placeholder colour not reflecting

### ISSUE THREAD

**Issue by imbudhiraja** [sbycrosz/react-native-credit-card-input#23]
Hi All,

I need to change the placeholder colour but it was not reflecting. It remains the default colour. 
When i try to change other text colours they got changed.
Here is sample code. 

<CreditCardInput
      requiresName={true}
      cardFontFamily={"Kabel Bk BT"}
      placeholderColor={"white"}
       inputContainerStyle={{
           borderBottomWidth: 1, borderBottomColor:Constants.Colors.White
       }}
      onChange={this._onChange}
      labelStyle={[styles.label,Constants.Fonts.content]}
      inputStyle={[styles.input,Constants.Fonts.content]}
     autoFocus={false}/>

**Comment by sbycrosz** [comment]
Thanks @imbudhiraja ! I just pushed a fix @0.3.3 🎉 

Also not that the font family might be displayed incorrectly on Android https://github.com/facebook/react-native/issues/4600

**Comment by imbudhiraja** [comment]
Thanks

**Comment by imbudhiraja** [comment]
Thanks Cheers
