### ISSUE TITLE
Can't unfocus (blur) from text input

### ISSUE THREAD

**Issue by fbele** [sbycrosz/react-native-credit-card-input#242]
Even though in Expo Snack I have tested and seen that tapping outside a text input does blur (unfocus) the field, I can't seem to have the option possible in my implementation.

As soon as any of the three fields is focused, I cannot blur or "get out" of that field. I can tap on any of the three and they are responding find and the card and data does get filled out, I just seem to not be able to unfocus the field.

Does anybody have the same issue? How can I close the keyboard and get out of the focus of an input?

Besides that, I am missing an ability to mark per text input the validation error. For example, I would like to mark the field with red color, if it's incorrect. I don't seem to be able to do that.

**Comment by fbele** [comment]
UPDATE: This is not an issue with this module itself, but rather of the React Native itself - sorry about that. So I found a different solution to make it work in my case.

**Comment by maymay36p** [comment]
f386fc3bfa1bd50a8ee442bd0617f972a5d7ffbf
