### ISSUE TITLE
LiteCreditCardInput input focusing breaks with RN version > 0.37 (Release Build Configuration)

### ISSUE THREAD

**Issue by andybangs** [sbycrosz/react-native-credit-card-input#26]
I recently noticed that focusing of CCInput components in LiteCreditCardInput is not working as expected only when my project's build configuration is set to Release. 

- I was using react-native-credit-card-input v0.2.6, but am experiencing this same issue with v0.3.3.
- I've confirmed this issue with React Native versions 0.38, 0.39, and 0.40.
- Temporarily reverting to React Native 0.37 has allowed me to work around this for now.

I'd appreciate any insight or ideas about why this might be happening.

Thanks!

**Comment by andybangs** [comment]
No longer able to reproduce this bug after upgrading to Xcode 8.2.1.

**Comment by sbycrosz** [comment]
Thanks for the update @andybangs ! 
Which version of Xcode did you use previously? 

-Sam

**Comment by andybangs** [comment]
@sbycrosz I was on 8.1.x. Still am unsure as to why this behavior was observed only for release builds.

**Comment by ryanbennettvoid** [comment]
I'm still noticing the same issue with Xcode 8.2.1 and React Native 0.43.1. It works fine in the simulator, but on the real device (iPhone 6s) the focus doesn't switch to the month input after the card number input is complete. Then it once you click the card button, it'll switch. Then once you tap a field, it'll switch back.

Confirmed that it only happens in release mode- works fine in debug mode.

**Comment by MattFoley** [comment]
I'm actively attempting to track down the problem here. I'm only able to reproduce this on an iPhone 6 so far.

**Comment by MattFoley** [comment]
@sbycrosz My guess at the moment is that this has to do with the legacy "ref" usage, instead of the function usage, and some other race condition inside React Native. I'm seeing this intermittently on multiple devices. Some launches of the app, this does not occur, some launches it does.

When the app ends up in this state, the refs seem to be pointing to the wrong values. Tapping on the CC field focuses the CC field, but switches the layout to the date/cvc layout, and vice versa.

**Comment by MattFoley** [comment]
So when in this state, `focused` seems to be correct, as `_iconToShow()` is definitely showing the right value. If I tap on the expiry field, the expiry field is focused, even though the layout switches to the number entry layout.

It seems that sometimes the bits that use `showRightPart` such as `showRightPart ? s.hidden : s.expanded` seem to be evaluating incorrectly.

**Comment by MattFoley** [comment]
@sbycrosz I need to put this down for the evening, but would you mine opening this issue up again? There's definitely something funky going on here.

**Comment by MattFoley** [comment]
I believe I've confirmed that this is related to the connectToState componentDidMount hack. After adding a timeout of 50ms to the setTimeout call, I've changed the behavior of the bug when it manifests. Will continue updating.
