### ISSUE TITLE
allowsScroll prop not working

### ISSUE THREAD

**Issue by dennishansen** [sbycrosz/react-native-credit-card-input#30]
Enabling horizontal scrolling would alleviate the issue of it being difficult to navigate left/right through input fields, however setting the prop does not work.

**Comment by imbudhiraja** [comment]
@dennishansen plz use like this. 

<CreditCardInput
              requiresName={true}
              allowScroll={false}
              placeholderColor={"gray"}/>

**Comment by dennishansen** [comment]
I cannot get this to work on android. Is it supported?

**Comment by sbycrosz** [comment]
It should be

**Comment by infaz** [comment]
For Android its not working
