### ISSUE TITLE
keyboardShouldPersistTaps true/false deprecated

### ISSUE THREAD

**Issue by CooLSeS** [sbycrosz/react-native-credit-card-input#31]
Warning: 'keyboardShouldPersistTaps={true}' is deprecated. Use 'keyboardShouldPersistTaps="always"' instead

**Comment by alexis1990** [comment]
+1

**Comment by alexis1990** [comment]
You need to use the keyboard and it works !

**Comment by CooLSeS** [comment]
#32

**Comment by sbycrosz** [comment]
Thanks again!
