### ISSUE TITLE
Warning: Failed prop type: FlipCard: prop type 'Style" is invalid; it must be a function, usually from React.PropTypes

### ISSUE THREAD

**Issue by sotomaque** [sbycrosz/react-native-credit-card-input#34]
<img width="748" alt="screen shot 2017-02-16 at 4 23 23 pm" src="https://cloud.githubusercontent.com/assets/7506954/23044141/8eb7cd1e-f464-11e6-98e1-273492df94b5.png">
<img width="751" alt="screen shot 2017-02-16 at 4 23 30 pm" src="https://cloud.githubusercontent.com/assets/7506954/23044142/8eb8fd06-f464-11e6-8530-cd7d723bc8ee.png">
<img width="279" alt="screen shot 2017-02-16 at 4 24 32 pm" src="https://cloud.githubusercontent.com/assets/7506954/23044143/8eba3252-f464-11e6-8595-3d52a60eb4e6.png">

**Comment by gcmartins93** [comment]
Actually, this is a react-native-flip-card issue. There is an [open thread](https://github.com/moschan/react-native-flip-card/issues/23) for that. They may be working on a fix.

**Comment by sbycrosz** [comment]
I guess we'll need to upgrade the react-native-flip-card dependency? I'll do it on the weekend.. (or PRs are always welcome!)

-Sam

**Comment by sbycrosz** [comment]
Should be fixed in 4.1
