### ISSUE TITLE
Porting to React for web?

### ISSUE THREAD

**Issue by bkrall** [sbycrosz/react-native-credit-card-input#35]
This repo looks amazing.

Not too familiar with React Native, how much work would it take to port this to React for the web?

Any info would be much appreciated.

**Comment by sbycrosz** [comment]
There isn't any plan yet, the UI will need to change drastically though..
Also the web already have similar project such as https://jessepollak.github.io/card/ or the react port https://github.com/shatran/card-react if you really need one

-Sam

**Comment by bkrall** [comment]
That makes sense, thanks. 

Just came across https://stripe.com/docs/elements which will fill my needs for now, appreciate the info.

**Comment by sbycrosz** [comment]
👍 Stripe elements looks really nice! Never know it existed
