### ISSUE TITLE
CardView prop for Text Color

### ISSUE THREAD

**Issue by l3wi** [sbycrosz/react-native-credit-card-input#48]
Looking for a prop to change the color of the baseText, placeholder & focused text on the CardView Component. 

I've changed the hardcoded values but everytime I "yarn upgrade" it overwrites the values. 

Could you please add this.

Thanks,
Lewis

**Comment by JesusMaterano** [comment]
+1

**Comment by JesusMaterano** [comment]
@l3wi Do you resolve this problem ? Let me know!

**Comment by Alb93** [comment]
+1
