### ISSUE TITLE
[Question]: Reseting Card FormData

### ISSUE THREAD

**Issue by tolu360** [sbycrosz/react-native-credit-card-input#5]
Hello @sbycrosz, thanks for sharing this package. Got a question, please is there a way to reset the   form data/values such as in a lifecycle event like `componentWillUnmount` or even after data is retrieved and form is submitted etc?

Thanks.

**Comment by sbycrosz** [comment]
Hey @tolu360,

The component will always start with an empty state (via `this.state = {}` on the constructor)

As for how to reset the form after data is retrieved and form is submitted, we did it by structuring the routes the following way:

```js
  ShoppingCart -->  Add Credit Card Page (with the CreditCardInput)
                      |
      <---------------+ 
  //  pops back to previousPage onSubmit 
  //  (effectively un-mounting CCInput & destroying the state)
        
```

Let me know if this answers your question!

**Comment by tolu360** [comment]
Thanks for your response and for sharing your insights from your usage in production, it's really enlightening. Perhaps, like you have shared, navigating away from the scene/screen where CCInput is mounted does settles it (I am still testing CCInput within the context of just a screen).

Being able to do something like `this.refs.CCInput.clear()` may be a great idea as well. Great work by the way!

**Comment by sbycrosz** [comment]
I think I'll park the `this.refs.CCInput.clear()` idea since it breaks the existing implementation (i.e. the `move to previous field when the input become empty` logic).

Also closing this issue, since most cases could be handled with just un-mounting the component
