### ISSUE TITLE
Attempting to use `this.refs.CCInput.setValues({ number: "4242" });` but receiving, "undefined is not an object."

### ISSUE THREAD

**Issue by Mimble-Wimble** [sbycrosz/react-native-credit-card-input#52]
I'm currently attempting to use `this.refs.CCInput.setValues({ number: "4242" });` in my component to update the number value generated in the `CreditCardInput` component, but keep receiving, "undefined is not an object." Anyone have any thoughts on how to get this to work? I've pasted a snippet of code below:

```

<CreditCardInput 
        ... 
/>

<TextInput
	onChangeText={(value) => this.refs.CCInput.setValues({ number: value })}
        ...
/>
```

**Comment by jjhesk** [comment]
```
<CreditCardInput 
      ref="CCInput" 
/>
```
should work

**Comment by Mimble-Wimble** [comment]
@jjhesk, thanks, but sadly no luck. Logging `this.refs` appears to return an empty Object. Possible a `bind.this` is needed somewhere?

**Comment by Mimble-Wimble** [comment]
I take it back, your solution worked! Thanks again, @jjhesk. My TextInput is updating the values as expected. It's my function that craps out on me when called for some reason:

```
const testSetValue = (value) => {
    this.refs.CCInput.setValues({ number: value });
}
``

**Comment by Mimble-Wimble** [comment]
Solved! I simply had to pull my function outside of `render()`
