### ISSUE TITLE
Plugin allows entering 18 digits as card number

### ISSUE THREAD

**Issue by alexsorokoletov** [sbycrosz/react-native-credit-card-input#55]
Hi! 
Thank you for the component.
The issue is not major, obviously.

Entering last digit of card, then switching to expiration and back using backspace allows entering 18 digits. Not sure, if this is a bug or feature.

<img width="394" alt="screenshot 2017-04-18 05 11 33" src="https://cloud.githubusercontent.com/assets/1788581/25123211/a019cb14-23f5-11e7-8835-4bda647bcab0.png">

Latest version

**Comment by ningacoding** [comment]
![image](https://user-images.githubusercontent.com/34582073/47034257-779fbb80-d13c-11e8-9bfb-3c18ea1f44e3.png)
Component allowing:
- Invalid card number length
- Invalid date values

Returning valid: true

**Comment by sailykeepitonthelow** [comment]
Hello @sbycrosz 

Are you able to resolve this issue? I am also facing the same? Please can any one help with this
