### ISSUE TITLE
Very slow when used on a mobile device but runs fine in xcode

### ISSUE THREAD

**Issue by TheIrvingBarajas** [sbycrosz/react-native-credit-card-input#56]
Hello!
Thank you so much for creating this component, it has been very useful.

When I was integrating this component into my application it would run super fast and smooth during development in xcode. But when I deployed to production it is super slow and laggy. 
Do you happen to know what I am doing wrong or is this a reoccurring issue.

Tested on multiple iPhones.

**Comment by nikolabrdaroski** [comment]
Hello, Did you managed to fix this ?
