### ISSUE TITLE
Improve set focus to previous field logic

### ISSUE THREAD

**Issue by sbycrosz** [sbycrosz/react-native-credit-card-input#7]
I'm writing this as documentations & pleas for help

Currently CCInput set focus to the previous field when a field become empty.  e.g. `when user changes expiry from "1" to "" with backspace button, CCInput will focus to number field`. This will not allow user to removes expiry without triggering the `set focus to the previous field` logic.

The better logic is to move to previous field when user press backspace on an empty field (following [stripe implementation](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPaymentCardTextField.m)). 

The catch is `onKeypress` prop is not available for RN Android atm, so some workaround might be needed.

PRs are welcome! 🎉

**Comment by rturk** [comment]
Maybe Simpler approach could be a setTimeout timer if nothing is pressed within 1s?

**Comment by sbycrosz** [comment]
Yeah, but that is kind of nondeterministic way of deciding user's intent.
I guess I'll close this until RN has onKeyPress on both platform
