### ISSUE TITLE
Card number input loses focus to expiry after 12 numbers entered

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [sbycrosz/react-native-credit-card-input#77]
Hi all, 

While trying to enter account numbers like 5017670000005900 the card number using the phone keypad text input loses focus after entering only 12 numbers instead of 16  and focus moves to expiry.  Couldn't find any props or options in documentation.

"react-native": "0.47.0",
"react-native-credit-card-input": "0.3.3"

Please Help.

**Comment by ignivaravinderrikhi** [comment]
Please help anyone.. Its urgent ..

**Comment by ismaro** [comment]
Hello,
You can navigate to node_modules/react-native-credit-card-input/src/CCFieldValidator.js file. 
then modify 20th line of the file.
const numberValidation = formValues.number;
replace that line with

var perCalculatedNumber = formValues.number;
    if(formValues.number.length>=16)
    {
      perCalculatedNumber = valid.number(formValues.number);
    }
    const numberValidation = perCalculatedNumber;
 
But if you do this then you will be able only to validate cards with min 16 char. in length.
Also keep in mind that once you do this, in a case you need to reinstall node_modeules folder you will need to correct it accordingly.
