### ISSUE TITLE
Using deprecated feature on <TextInput>

### ISSUE THREAD

**Issue by tobyglover** [sbycrosz/react-native-credit-card-input#81]
The Message:

`Warning: 'keyboardShouldPersistTaps={true}' is deprecated. Use 'keyboardShouldPersistTaps="always"' instead`

**Comment by dallen4** [comment]
I am also having this issue, can this please be fixed.

**Comment by sbycrosz** [comment]
I don't think we have 'keyboardShouldPersistTaps={true}` anywhere in  the source though

**Comment by wtglover** [comment]
PR #47 (https://github.com/sbycrosz/react-native-credit-card-input/pull/47) fixes it. Just need to be merged.
