### ISSUE TITLE
get error immediately when i import

### ISSUE THREAD

**Issue by liu-yuhuan** [sbycrosz/react-native-credit-card-input#84]
i got an error after i import the component
did anyone got same error??

[https://imgur.com/05jKbXR](url)

Unhandled JS Exception: Cannot read property 'string' of undefined
Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by phanoophong** [comment]
error because react 16 not have Proptypes  but this lib use PropTypes from react-native.
You can edit lib and Replace Proptype with prop-type  ("(https://www.npmjs.com/package/prop-types") and worked find.

**Comment by liu-yuhuan** [comment]
thank you !! it's works 
but another error shows
Unhandled JS Exception: Error: The <Image> component cannot contain children. If you want to render content on top of the image, consider using aboslute positioning.

error only shows when i use CreditCardInput

**Comment by liu-yuhuan** [comment]
i solved by change CardView.js
switch Image to ImageBackground
