### ISSUE TITLE
[Android] Card image is cropped below when using cardScale prop

### ISSUE THREAD

**Issue by LRNZ09** [sbycrosz/react-native-credit-card-input#95]
I'm using cardScale property and on Android only the image is cropped, see the screenshot attacched:
![screenshot_1516196458](https://user-images.githubusercontent.com/13508373/35045732-1681cc08-fb95-11e7-94a3-3d0a1fa17b4c.png)

**Comment by andidev** [comment]
Will be fixed by PR #103 when it gets merged

**Comment by LRNZ09** [comment]
This library seems abandoned, I'm going to close this issue.
