### ISSUE TITLE
setValues: this.refs object is empty

### ISSUE THREAD

**Issue by GarimaMathur07** [sbycrosz/react-native-credit-card-input#96]
@sbycrosz Set values into credit card form:

When i use credit card input library in my project and i have to set card values after card scan then this.refs object is empty from this line:
`this.refs.CCInput.setValues({ number: "4242" });` 

So, how can i set values after card scanning.

**Comment by brasiltrocador** [comment]
<CreditCardInput
                            ref={(c) => this.CCInput = c} -----> include
                            autoFocus

                            requiresName
                            requiresCVC
                            requiresPostalCode


                            labelStyle={s.label}
                            inputStyle={s.input}
                            validColor={"black"}
                            invalidColor={"red"}
                            cvc={'123'}
                            placeholderColor={"darkgray"}


                            onFocus={this._onFocus}
                            onChange={this._onChange} />



use this
_post = () =>{
        this.CCInput.setValues({ number: "4242" });
    }

**Comment by GauravRana** [comment]
`const refContainer  = useRef(null);`
